# Generated by Django 4.0.5 on 2022-06-08 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=255, unique=True, verbose_name='Employee Id')),
                ('employee_name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2, verbose_name='Gender')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Email')),
                ('image_path', models.CharField(blank=True, max_length=1000, verbose_name='Profile Image Path')),
                ('Role', models.CharField(choices=[('All', 'All'), ('Admin', 'Admin'), ('Project Manager', 'Project Manager'), ('Team Leader', 'Team Leader'), ('Leader', 'Leader'), ('Member', 'Member')], max_length=20, verbose_name='Role')),
                ('pwd_reset_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Change password time', null=True, verbose_name='Change password time')),
            ],
            options={
                'verbose_name': 'Employee Info',
                'verbose_name_plural': 'Employee Info',
                'ordering': ['id'],
                'managed': True,
                'unique_together': {('phone', 'email')},
            },
        ),
    ]
