# Generated by Django 4.0.5 on 2022-06-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resource'), ('DEV', 'Developement'), ('VC', 'Vitual and Creative Designs'), ('BS', 'Bussiness Support Executives')], max_length=3, verbose_name='Department'),
        ),
    ]
