# Generated by Django 4.0.5 on 2022-06-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('All', 'All'), ('Admin', 'Admin'), ('Editor', 'Editor'), ('Member', 'Member')], max_length=20, verbose_name='Role'),
        ),
    ]
