# Generated by Django 4.0.5 on 2022-06-08 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('Date', models.DateTimeField(auto_created=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.employee')),
                ('isPresent', models.BooleanField(default=False)),
                ('Comments', models.CharField(max_length=200, null=True, verbose_name='Comments')),
                ('added_by', models.CharField(max_length=100, verbose_name='Entry By')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
                'ordering': ['Date'],
            },
        ),
    ]
