# Generated by Django 4.0.5 on 2022-06-09 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(choices=[('All', 'All'), ('Admin', 'Admin'), ('Editor', 'Editor'), ('Member', 'Member')], max_length=20, verbose_name='Role')),
                ('employee_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Employee Id')),
                ('first_name', models.CharField(max_length=125, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=125, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2, verbose_name='Gender')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('picture', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Employee Info',
                'verbose_name_plural': 'Employee Info',
                'ordering': ['employee_id'],
                'managed': True,
                'unique_together': {('phone', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('Date', models.DateTimeField(auto_created=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hr.employee')),
                ('isPresent', models.BooleanField(default=False)),
                ('Comments', models.CharField(max_length=200, null=True, verbose_name='Comments')),
                ('added_by', models.CharField(max_length=100, verbose_name='Entry By')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
                'ordering': ['Date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('office_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, choices=[('HR', 'Human Resource'), ('DEV', 'Developement'), ('VC', 'Vitual and Creative Designs'), ('BS', 'Bussiness Support Executives')], max_length=3, verbose_name='Department')),
                ('section', models.CharField(choices=[('S', 'Sale'), ('O', 'Operation')], max_length=2, verbose_name='Section')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ServiceHistory', to='hr.employee')),
            ],
        ),
    ]
